# Generated by Django 2.1.7 on 2019-04-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=30)),
                ('content_text', models.CharField(max_length=140)),
            ],
        ),
    ]
